<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2016 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!DOCTYPE  employee[
        <!ELEMENT employee ( blah?| first_name?| last_name?| birth_date?| height?| weight?| active?)+>
        <!ATTLIST employee
                id CDATA #IMPLIED
                >
        <!ELEMENT blah EMPTY>
        <!ATTLIST blah something CDATA "0">
        <!ELEMENT first_name (#PCDATA)>
        <!ELEMENT last_name (#PCDATA)>
        <!ELEMENT birth_date (year,month,day)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT month (#PCDATA)>
        <!ELEMENT day (#PCDATA)>
        <!ELEMENT height (#PCDATA)>
        <!ATTLIST height units CDATA "0">
        <!ELEMENT weight (#PCDATA)>
        <!ATTLIST weight units CDATA "0">
        <!ELEMENT active (#PCDATA)>
        ]>
<employee id="${id_var}">
  <blah something="that"/>
  <first_name>Jim</first_name>
  <last_name>Smith</last_name>
  <birth_date>
    <year>1970</year>
    <month>6</month>
    <day>15</day>
  </birth_date>
  <height units="ft">5.8</height>
  <weight units="lbs">200</weight>
  <active>true</active>
</employee>